name: calculator
version: 0.1.0
author: goclaw
description: Mathematical calculations and conversions
category: builtin
tags: [math, calculator, conversion]

tools:
  - name: calculate
    description: Evaluate a mathematical expression
    parameters:
      expression:
        type: string
        description: Mathematical expression to evaluate
        required: true

  - name: convert_units
    description: Convert between units
    parameters:
      value:
        type: number
        required: true
      from_unit:
        type: string
        required: true
      to_unit:
        type: string
        required: true

system_prompt: |
  You can perform mathematical calculations and unit conversions.
  Use calculate for math expressions.
  Use convert_units for unit conversions.

triggers:
  - "calculate"
  - "what is"
  - "convert"
  - "calcular"
  - "converter"
  - "quanto é"
